#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
file_h="holbertonschool"

if [ -e "$file_h" ]
then

    echo "holbertonschool file exists"
    if [ -s "$file_h" ]
    then
        echo "Bestschool file is not empty"
    else
        echo "bestschool file is empty"
    fi

    if [ -f "$file_h" ]
    then
        echo "Bestschool is a regular file"
    fi
else
    echo "bestschoolschool file does not exist"
fi
